name: JS test & check

on:
  pull_request:
    paths:
      - 'front/*'

jobs:
  check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - working-directory: front
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, lint & type-check and test
      run: |
        yarn install
        yarn run lint --if-present
        yarn run check --if-present
        yarn run test --if-present
      env:
        CI: true
